### ISSUE TITLE
Update to redstone 0.4.1

### ISSUE THREAD

**Issue by rtclauss** [IBM/keyprotect-python-client#4]
Hello keyprotect maintainers!

The latest release of redstone supports additional functions, such as the creation of key rings.  Any chance of updating the pip dependencies to pull in the 0.4.1 redstone release?
Thanks!

**Comment by mrodden** [comment]
@rtclauss Sorry, missed your issue here. I pay more attention to the main repo Issues and not this one as much.

Let me go do a version rev and some testing to make sure nothing is broken with the new versions.

**Comment by mrodden** [comment]
Released 2.1.0 which should be tied to 0.5.x of redstone

see commit 4300c1cb60 for details
